dist: bionic


sudo: false

language:
  - python

python:
  - "3.7"
  - "3.8"
  - "3.9"

install:
  - pip install -r requirements.txt
  - pip install codecov

os:
  - linux

script: 'make all'

notifications:
  email:
    on_success: never
    on_failure: change

after_success:
  # Push the code coverage result to codecov:
  - codecov
